server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/example
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true